sudo: false
language: cpp
os:
  - linux
  - osx
compiler:
  - clang
jdk:
  - oraclejdk7

addons:
   apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: ['clang-3.6' , 'zlib1g-dev', 'libbz2-dev', 'libsnappy-dev', 'curl']
env:
  # Run [oo, db_test2[ -> {db_test{
  - JOB_NAME=unittests ROCKSDBTESTS_END=db_test2
  # Run [db_test2, fault_injection_test[
  - JOB_NAME=unittests ROCKSDBTESTS_START=db_test2 ROCKSDBTESTS_END=fault_injection_test
  # Run [fault_injection_test, ttl_test[
  - JOB_NAME=unittests ROCKSDBTESTS_START=fault_injection_test ROCKSDBTESTS_END=ttl_test
  # Run [ttl_test, oo[
  - JOB_NAME=unittests ROCKSDBTESTS_START=ttl_test
  # Run java tests
  - JOB_NAME=java_test
  # Build ROCKSDB_LITE
  - JOB_NAME=lite_build

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == 'linux' ]]; then CXX=clang++-3.6; fi
  # Limit the maximum number of open file descriptors to 8192
  - ulimit -n 8192 || true

script:
  - if [[ "${JOB_NAME}" == 'unittests' ]]; then OPT=-DTRAVIS V=1 make -j8 check_some; fi
  - if [[ "${JOB_NAME}" == 'java_test' ]]; then OPT=-DTRAVIS V=1 make clean jclean rocksdbjava jtest; fi
  - if [[ "${JOB_NAME}" == 'lite_build' ]]; then OPT="-DTRAVIS -DROCKSDB_LITE" V=1 make -j8 static_lib; fi
notifications:
    email:
      - leveldb@fb.com
    webhooks:
      - https://buildtimetrend.herokuapp.com/travis
