name: post-pmd-steps
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v4.0.0
    with:
      name: pmd-report
      path: "${{ github.workspace }}/java/target/pmd.xml"
  - uses: actions/upload-artifact@v4.0.0
    with:
      name: maven-site
      path: "${{ github.workspace }}/java/target/site"
