name: post-steps
description: Steps that are taken after a RocksDB job
inputs:
  artifact-prefix:
    description: Prefix to append to the name of artifacts that are uploaded
    required: true
    default: "${{ github.jobs[github.job].name }}"
runs:
  using: composite
  steps:
  - name: Upload Test Results artifact
    uses: actions/upload-artifact@v4.0.0
    with:
      name: "${{ inputs.artifact-prefix }}-test-results"
      path: "${{ runner.temp }}/test-results"
  - name: Upload DB LOG file artifact
    uses: actions/upload-artifact@v4.0.0
    with:
      name: "${{ inputs.artifact-prefix }}-db-log-file"
      path: LOG
  - name: Compress Test Logs (on Failure)
    run: tar -cvzf t.tar.gz t
    if: ${{ failure() }}
    shell: bash
  - name: Upload Test Logs (on Failure) artifact
    uses: actions/upload-artifact@v4.0.0
    with:
      name: "${{ inputs.artifact-prefix }}-failure-test-logs"
      path: t.tar.gz
  - run: |-
      mkdir -p ${{ runner.temp }}/core_dumps
      cp core.* ${{ runner.temp }}/core_dumps
    if: ${{ failure() }}
    shell: bash
  - name: Upload Core Dumps artifact
    uses: actions/upload-artifact@v4.0.0
    with:
      name: "${{ inputs.artifact-prefix }}-core-dumps"
      path: "${{ runner.temp }}/core_dumps"
