name: facebook/rocksdb/benchmark-linux
on:
  schedule:
  - cron: 5 17 * * *  # Every day 5:17 UTC, 22:00 PST

jobs:
  benchmark-linux:
    if: ${{ github.repository_owner == 'facebook' }}
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: "./.github/actions/build-for-benchmarks"
    - uses: "./.github/actions/perform-benchmarks"
    - uses: "./.github/actions/post-benchmarks"
