name: Check buckifier up-to-date
on: [push, pull_request]
jobs:
  check:
    name: Check buckifier
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1

    - name: Buckify
      run: python buckifier/buckify_rocksdb.py

    - name: Compare
      run: bash -c 'TMP="$(git diff TARGETS | head -n 1)"; if [ -z "$TMP" ]; then exit 0; else exit 1; fi'
